//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMessagingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminGroup
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int AccountId { get; set; }
    
        public virtual Acccount Acccount { get; set; }
        public virtual Group Group { get; set; }
    }
}
