//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMessagingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Chat
    {
        public int Id { get; set; }
        public Nullable<int> MessageId { get; set; }
        public Nullable<int> LastSeenMessageId { get; set; }
    }
}
