//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMessagingAppUnitTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialMessagingAppEntities : DbContext
    {
        public SocialMessagingAppEntities()
            : base("name=SocialMessagingAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acccount> Acccounts { get; set; }
        public virtual DbSet<AdminGroup> AdminGroups { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<GroupAccount> GroupAccounts { get; set; }
        public virtual DbSet<MediaFile> MediaFiles { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Text> Texts { get; set; }
    }
}
